version: "3.9"
services:
  placita:
    image: placita:$TAG
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: placita
    volumes:
      - ./app/components:/usr/src/app/components
      - ./app/controllers:/usr/src/app/controllers
      - ./app/data:/usr/src/app/data
      - ./app/handlebars:/usr/src/app/handlebars
      - ./app/models:/usr/src/app/models
      - ./app/public:/usr/src/app/public
      - ./app/routes:/usr/src/app/routes
      - ./app/utils:/usr/src/app/utils
      - ./app/views:/usr/src/app/views
      - ./app/app.js:/usr/src/app/app.js
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - placita-network

networks:
  placita-network:
    driver: bridge
