version: "3.9"
services:
  placita:
    image: placita:$TAG
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: placita
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - placita-network

networks:
  placita-network:
    driver: bridge
