FROM node:14-buster AS build

LABEL decription="Development image for Placita."

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

FROM gcr.io/distroless/nodejs:14

WORKDIR /usr/src/app

COPY --from=build /usr/src/app .

HEALTHCHECK --interval=1m --timeout=5s --retries=2 \
  CMD curl -f http://localhost || exit 1

CMD ["app.js"]