version: "3.9"
services:
  placita:
    restart: always
    container_name: placita
    image: index.docker.io/starlightromero/placita
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - placita-network

networks:
  placita-network:
    driver: bridge
