version: "3.9"
services:
  node:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: placita-node
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - placita-network

networks:
  placita-network:
    driver: bridge
