FROM node:lts-alpine

LABEL decription="Development image for StockStalker backend."

WORKDIR /app

COPY package.json .

COPY yarn.lock .

RUN yarn install

COPY . .

EXPOSE 3000

CMD ["yarn", "start-dev"]