version: "3.9"
services:
  placita:
    image: placita:$TAG
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: placita
    volumes:
      - ./components:/usr/src/app/components
      - ./controllers:/usr/src/app/controllers
      - ./data:/usr/src/app/data
      - ./handlebars:/usr/src/app/handlebars
      - ./models:/usr/src/app/models
      - ./public:/usr/src/app/public
      - ./routes:/usr/src/app/routes
      - ./utils:/usr/src/app/utils
      - ./views:/usr/src/app/views
      - ./app.js:/usr/src/app/app.js
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - placita-network

networks:
  placita-network:
    driver: bridge
